version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www:cached
    ports:
      - 80:80
    links:
      - app
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www:cached
    depends_on:
      - db_name

  crm_mysql_db:
    image: mysql:5.7
    container_name: db_name
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=user_name
      - MYSQL_PASSWORD=secret